export const PRODUCT_START = 'PRODUCT_START'
export const PRODUCT_LOADED = 'PRODUCT_LOADED'
export const PRODUCT_ERROR = 'PRODUCT_ERROR'


export const SERVICES_START = 'SERVICES_DATA_START'
export const SERVICES_LOADED = 'SERVICES_DATA_LOADED'
export const SERVICES_ERROR = 'SERVICES_DATA_ERROR'

export const TABLE_START = 'TABLE_START'
export const TABLE_LOADED = 'TABLE_LOADED'
export const TABLE_ERROR = 'TABLE_ERROR'

export const EXP_START = 'EXP_START'
export const EXP_LOADED = 'EXP_LOADED'
export const EXP_ERROR = 'EXP_ERROR'
